server:
  port: 8762
  
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/sakhtar/git/shopping-micro-service/configuration-server/src/main/resources/config/cart-service,
                            file:///C:/Users/sakhtar/git/shopping-micro-service/configuration-server/src/main/resources/config/payment-service,
                            file:///C:/Users/sakhtar/git/shopping-micro-service/configuration-server/src/main/resources/config/zuul-server,
                            file:///C:/Users/sakhtar/git/shopping-micro-service/configuration-server/src/main/resources/config/eureka-server,
                            file:///C:/Users/sakhtar/git/shopping-micro-service/configuration-server/src/main/resources/config/hystrix-dashboard
                            

