server:
  port: 7005
  servlet:
    context-path: /auth
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    
  